export {default as Tab1Recommend} from './tab1-recommend'
export {default as Tab2MusicList} from './tab2-musicList'
export {default as Tab3DJ} from './tab3-dj'
export {default as Tab4TopList} from './tab4-toplist'
export {default as Tab5Artist} from './tab5-artist'
export {default as HighQualityMusicList} from './tab2-musicList/highQualityList'